# Generated by Django 3.1.4 on 2020-12-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuomiphp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeribitFundingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
